deployScripts:
  start:
    - npm install
    - pm2 -s start --name=hello-world-example index.js
  delete:
    - pm2 -s delete hello-world-example
  restart:
    - npm install
    - pm2 -s restart hello-world-example
